### ISSUE TITLE
https://domain/ci/logs/ no more accessible since last version

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/yunorunner_ynh#39]
### Describe the bug

*Since last version, https://domain/ci/logs/ can't be access.*

### Context

- https://ci-apps.yunohost.org/ci/logs/ works
- https://ci-apps-unstable.yunohost.org/ci/logs doesn't work
- https://ci-apps-dev.yunohost.org/ci/logs doesnt' work

**Comment by Salamandar** [comment]
Fixed. Wrong chmod on upgrade.
