### ISSUE TITLE
Level 6

### ISSUE THREAD

**Issue by yalh76** [YunoHost-Apps/yunorunner_ynh#9]
### Describe the bug

*The app is level 6* because package_linter look the package repository at `https://github.com/YunoHost-Apps/yunorunner_ynh` not `https://github.com/YunoHost-Apps/yunorunner_ynh_core`

Do we change the repository name ?

**Comment by alexAubin** [comment]
zblerg yeah there's kind of an implicit standard about the repo *has* to be named "$app_ynh" ... Naively I guess we could just rename to yunorunner_ynh, appart if there's really something related to the "core", or "official yunohost stuff" i guess

**Comment by yalh76** [comment]
As far as I've seen, there nothing special about core...

**Comment by yalh76** [comment]
And @kay0u, what's your opinion ?

**Comment by kay0u** [comment]
I think we can go for it. I'm just wondering what will happen when updating this app

**Comment by yalh76** [comment]
change made ^^
